### ISSUE TITLE
OCR not execute inside the Container

### ISSUE THREAD

**Issue by aswinkumarrhex** [otiai10/gosseract#99] opened 2017-12-25 09:39 UTC
Hi
installed GO -TESSARECT inside the container fabric-tools. But application still not able to recognize the same at runtime.
![sm1](https://user-images.githubusercontent.com/20457599/34337485-9b964792-e985-11e7-9a85-5459db689f6e.png)
![sm2](https://user-images.githubusercontent.com/20457599/34337486-9c620ada-e985-11e7-9104-b833d00c490d.png)

**Comment by otiai10** [comment] 2017-12-27 05:37
Hi, @aswinkumarrhex 

I can have time to have a look today, please stay tune.

Btw, at least, it's definitely possible to have gosseract run on docker containers, as I'm using containers for runtime tests.

FYI https://github.com/otiai10/gosseract/blob/master/test/runtime#L76-L78

**Comment by otiai10** [comment] 2017-12-27 05:49
@aswinkumarrhex I have some questions before starting the tackle.

1. Are you able to execute **any other golang packages** instead of `gosseract`
2. Where can I have `instantiate_chaincode.js` source code?
3. Please try `docker exec -it e60f7ad09048 ls -la /opt/gopath/src/github.com/otiai10` to check if gosseract exists
4. Paste your output as texts with using code block instead of pictures, like this ↓

```
foo bar
```

so that I can grep some keywords

**Comment by aswinkumarrhex** [comment] 2017-12-27 06:38
1) I haven't explored with any other golang packages. 
if you have any suggestions I am  happy to try it out ! 
2) Here is the code  - part of the demo we are exploring
https://github.com/IBM-Blockchain/marbles/tree/v4.0/scripts
3) Yes it does exist....

```
debug: [fcw] Instantiating Chaincode peer_urls=[grpc://localhost:7051], channel_id=mychannel, chaincode_id=marbles, chaincode_version=v4, cc_args=[12345], ssl-target-name-override=null, pem=null, grpc.http2.keepalive_time=300, grpc.keepalive_time_ms=300000, grpc.http2.keepalive_timeout=35, grpc.keepalive_timeout_ms=3500
debug: [fcw] Sending instantiate req targets=[grpc.http2.keepalive_time=300, grpc.keepalive_time_ms=300000, grpc.http2.keepalive_timeout=35, grpc.keepalive_timeout_ms=3500, grpc.primary_user_agent=grpc-node/1.6.6, _url=grpc://localhost:7051, addr=localhost:7051, , _request_timeout=90000, , _name=null], chaincodeId=marbles, chaincodeVersion=v4, fcn=init, args=[12345], 0=179, 1=206, 2=138, 3=104, 4=161, 5=5, 6=47, 7=234, 8=39, 9=120, 10=184, 11=76, 12=98, 13=211, 14=115, 15=1, 16=148, 17=53, 18=84, 19=87, 20=205, 21=45, 22=207, 23=70, _transaction_id=85dd037b9fb1f292a3bb99464570b396bedc34d56a1a5b9f9aecd320af9bece8
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "chaincode/input/src/marbles/marbles.go:28:2: cannot find package "github.com/hyperledger/otiai10/gosseract" in any of:
        /opt/go/src/github.com/hyperledger/otiai10/gosseract (from $GOROOT)
        /chaincode/input/src/github.com/hyperledger/otiai10/gosseract (from $GOPATH)
        /opt/gopath/src/github.com/hyperledger/otiai10/gosseract
"
    at /opt/Workspace/Marbles_TFAPP/node_modules/grpc/src/node/src/client.js:554:15
error: [fcw] Failed to obtain endorsement for transaction. code=2,
error: [fcw] Error in instantiate catch block object code=2,
---------------------------------------
info: Instantiate done. Errors: parsed=Blockchain network error -       /opt/go/src/github.com/hyperledger/otiai10/gosseract (from $GOROOT)
        /chaincode/input/src/github.com/hyperledger/otiai10/gosseract (from $GOPATH)
        /opt/gopath/src/github.com/hyperledger/otiai10/gosseract
", raw=[code=2, ]



==================================================================================================


root@cch1utbloc01:/opt/Workspace/fabric-samples/fabcar# docker exec -it 2b1f578a3934 bash
root@2b1f578a3934:/opt/gopath/src/github.com/hyperledger/fabric/peer# cd ../../
root@2b1f578a3934:/opt/gopath/src/github.com/hyperledger# ls
fabric  otiai10
root@2b1f578a3934:/opt/gopath/src/github.com/hyperledger#


```

**Comment by otiai10** [comment] 2017-12-27 08:56
- [ok] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/scripts/instantiate_chaincode.js#L39
- [ok] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/scripts/instantiate_chaincode.js#L57
- [ok] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/utils/fc_wrangler/index.js#L24-L26
- [ok] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/utils/fc_wrangler/deploy_cc.js#L82
- [ok] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/utils/fc_wrangler/deploy_cc.js#L99
    - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/Channel.js#L1139
    - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/Channel.js#L1140
    - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/Channel.js#L1167
    - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/Channel.js#L1249
        - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/client-utils.js#L66
            - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/client-utils.js#L73
            - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/Peer.js#L90
            - https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/protos/peer/peer.proto#L36
            - https://github.com/hyperledger/fabric/blob/d30b129e1b791ed4c8708675b5034c50f720dcf6/core/endorser/endorser.go#L370
            - // 
        - [NG] https://github.com/hyperledger/fabric-sdk-node/blob/6f7310ccda8648473d0f794e28c5b390ac030480/fabric-client/lib/client-utils.js#L80
- [NG] https://github.com/IBM-Blockchain/marbles/blob/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148/utils/fc_wrangler/deploy_cc.js#L135

**Comment by otiai10** [comment] 2017-12-27 09:12
@aswinkumarrhex 

As having read some code, it was hard to identify issues from source code without reproducing.
Give me a way to reproduce your problem.

Anyway, I don't think this is a problem of `gosseract` because `gosseract` is working on containers [as tests](https://github.com/otiai10/gosseract/tree/master/test/runtimes), which can be executed on your local and also on Travis-CI (or any other runtime with Docker of course).

Though I'm still not sure what you are trying to do, you should separate some points,

1. `github.com/otiai10/gosseract` is existing **on the runtime which imports "github.com/otiai10/gosseract"**
2. if `hyperledger/fabric-tools` is really the runtime which imports "github.com/otiai10/gosseract"
3. if other golang packages can be used as you expected and **especially not** for "gosseract"

**Comment by otiai10** [comment] 2018-01-24 01:28
if there is no longer any response, I would close this issue by 24H

**Closed** 2018-01-25 02:23 UTC
